### ISSUE TITLE
TheAudioDB image cache

### ISSUE THREAD

**Issue by zag2me** [lidarr/LidarrAPI.Metadata#132]
Hey i'm the admin on TADB, I noticed Lidarr showing up in the logs a lot recently and our bandwidth has gone crazy. Can I ask how it works? I don't see any API key associated with this project...

**Comment by mreid-tt** [comment]
Has there been any official resolution to this issue?

**Comment by zag2me** [comment]
Sadly had to ban it for not using correct API keys.

**Comment by ta264** [comment]
@zag2me is there something we can change our side so you'll unban it? We are currently using a patron key to get the URLs then serving those via our metadata aggregation service.

**Comment by cactushydrocodone** [comment]
gentle push @zag2me 
Is there something the lidarr project can do?
