### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by count00zero** [lidarr/LidarrAPI.Metadata#139]
Hi there, I tried to get your Metadataserver running and the setup went great (and long - as proposed ).

But after starting (i.e. the crawler) I get the following error:
socket.gaierror: [Errno -2] Name or service not known

Full log included; maybe someone could help?
[crawler.log](https://github.com/lidarr/LidarrAPI.Metadata/files/3808086/crawler.log)

Thanks and best regards,
count!

**Comment by ta264** [comment]
A personal metadata isn't really something we support (and it offers no benefits) but jump on the lidarr discord and I can see what I can do
