### ISSUE TITLE
Searching for some bands don't seem to work.

### ISSUE THREAD

**Issue by Logos302** [lidarr/LidarrAPI.Metadata#14]
Musicbrainz url https://musicbrainz.org/artist/7f41ac4b-9359-4f77-93ec-7c404f727f40.
 https://musicbrainz.org/artist/93e747b8-2896-439d-8c46-29158e8cff90
https://musicbrainz.org/recording/3cae81cd-8863-4eea-b7f8-9260bca34382 
https://musicbrainz.org/artist/1f9df192-a621-4f54-8850-2c5373b7eac9

**Comment by danielunderwood** [comment]
The first (Teaze) has been fixed by 7482dd6, but you won't see the change on your side until that change is merged. The PR being merged should show up in these comments.

I didn't see an issue on the second (Toy-Box). What issue did you see with it?

The third is a recording, which we don't support adding at the moment. The fourth (Beethoven) takes too long to query, so we'll have to look to see what we can do to speed up large queries.

**Comment by Logos302** [comment]
Toy-box returns the wrong information.  and sorry I grabbed the wrong link for bach, it should be this I think https://musicbrainz.org/artist/24f1766e-9635-4d58-a4d4-9413f9f98a4c.  But I couldn't get it to find it. It also could be because it's all compilation albums.  beethoven may be the same problem.

**Comment by Logos302** [comment]
And while I found bach and beetthoven it will not import.  Teaze now works, toy-box is hard to import, but as said has the wrong description.  (just tried again).

**Comment by danielunderwood** [comment]
I'll have to look at Toy-Box. I see now that it's getting the data from the wrong wikipedia page even though the musicbrainz db has the correct page link. Is there anything else wrong with Toy-Box?

I've had to blacklist Beethoven and Bach for the moment, so you'll probably start getting an immediate fail when importing them. They have so many albums that our query is running into issues, so we'll have to see what we can do.

**Comment by Qstick** [comment]
Another one: Blue Oyster Cult should find Blue Öyster Cult

**Comment by Tdotsown** [comment]
Unable to add Destiny's Child 
https://musicbrainz.org/artist/a796b92e-c137-4895-9c89-10f900617a4f/details

**Comment by ta264** [comment]
I believe all these search issues should now be resolved.
