### ISSUE TITLE
dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by fabiovalentino** [lidarr/LidarrAPI.Metadata#144]
Hi,
I've followed every step in the installation guide, I don't understand if i did something wrong but now i am stuck on the last step of this:
 
```
docker-compose build
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
docker-compose exec musicbrainz /createdb.sh -fetch
docker-compose exec sir make install
docker-compose exec sir make index
```

Looks like make index is taking forever (8+ hours)

lidarrapimetadata_metadata-latest_1 is restarting forever

If i exec " docker logs lidarrapimetadata_metadata-latest_1 " I see this error:

`ValueError: dictionary update sequence element #0 has length 1; 2 is required`

Can anyone help me solve this?

Thanks

**Comment by ta264** [comment]
We don't support local installs of the metadata api, and it's not necessary.  Please just use the mirror we provide.
