### ISSUE TITLE
Cache expiration for new releases

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/LidarrAPI.Metadata#49]
Cached responses may be returned after an artist has had a new release. Purge cache of artist responses when there are updates. Maybe scheduled task?

**Comment by Qstick** [comment]
Do we already have an expiration on cache? Maybe a day would be fine since we don’t have updates as often as tv shows

**Comment by danielunderwood** [comment]
Charts expire in a week and everything else is a day. Our cache is set up to discard the closest to expiring first, which I think has made this issue not a problem. It would be nice to capture db updates and purge the cache of any changes, but that may be a larger task than it's worth.

**Comment by ta264** [comment]
Cache is now automatically invalided on musicbrainz updates
