### ISSUE TITLE
Missing overviews

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/LidarrAPI.Metadata#55]
Missing overviews for artists with valid wikipedia links, such as `93bd1037-d736-42ca-93c3-c397f2cb1165` and `4f93401e-f3dd-4961-8b4e-708be531c3ce`. Seems that MediaWikiAPI either doesn't like encoded names or doesn't like non en.wikipedia sites.

**Comment by danielunderwood** [comment]
https://sentry.io/lidarr/metadata-api/issues/520521268/

Fixed symptom, but runs into `KeyError` with `30389ce4-1abf-4093-b5ed-64a3dd1dd734`.

**Comment by danielunderwood** [comment]
Check with changes in #80.

**Comment by Qstick** [comment]
Still no go after #80
