### ISSUE TITLE
IndexError: list index out of range, metadata doesn’t handle mbid that are not valid

### ISSUE THREAD

**Issue by Qstick** [lidarr/LidarrAPI.Metadata#6]
https://sentry.io/lidarr/metadata-api/issues/355089233/

```
IndexError: list index out of range
(3 additional frame(s) were not displayed)
...
  File "lidarrmetadata/api.py", line 70, in get_artist_info
    artist = artist_providers[0].get_artist_by_id(mbid)

IndexError: list index out of range
```

**Comment by Qstick** [comment]
This occurs when user searches by mbid, metadata does not handle below request.

`
[Trace] HttpClient: Res: [GET] https://api.lidarr.audio/api/v0/artists/c48b8ed2-46c5-4e51-9bea-5a37fcd0053b/?primTypes=Album&secTypes=Studio: 500.InternalServerError
{
  "error": "list index out of range"
}
`

**Comment by dabates** [comment]
Just for some more information on this one.. it seemed to fail on one sepecific artist.. I'm going to track that down and see what's going on.. unless @danielunderwood want's to track it.. this is the artist ID I was using: `c48b8ed2-46c5-4e51-9bea-5a37fcd0053b` or `lidarr:c48b8ed2-46c5-4e51-9bea-5a37fcd0053b` inside the ui

**Comment by Qstick** [comment]
Changed title, c48b8ed2-46c5-4e51-9bea-5a37fcd0053b is a label not an artist. But we should likely still handle by returning blank list or some type of response

**Comment by danielunderwood** [comment]
This should be the same as #5 since that's an invalid UUID. I was mainly planning on validating that UUID and returning a 400 if it isn't valid. Should the case that the UUID is valid, but for the wrong resource fall under the same error?
