### ISSUE TITLE
Add genres

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/LidarrAPI.Metadata#72]
For lidarr/Lidarr#426.

**Comment by danielunderwood** [comment]
https://blog.metabrainz.org/2018/11/02/musicbrainz-introducing-genres/

**Comment by Qstick** [comment]
Q2 Schema change should make this much easier. Issue for moving Genres to their own table is here <https://tickets.metabrainz.org/browse/MBS-9491>

**Comment by ta264** [comment]
This has been added
