### ISSUE TITLE
Old caching used for fanart requests

### ISSUE THREAD

**Issue by danielunderwood** [lidarr/LidarrAPI.Metadata#81]
`util.Cache` is still used for fanart request caching. This could cause images to be cached until the server is restarted along with continually increasing memory usage. Check for usages of the class linked below.

https://github.com/lidarr/LidarrAPI.Metadata/blob/e8abebcfb3fdbec8fa2bc53d4ad5bd3a5bef8366/lidarrmetadata/util.py#L128

**Comment by ta264** [comment]
Fixed in #125
