### ISSUE TITLE
Punctuation not properly de-internationalized

### ISSUE THREAD

**Issue by rootwyrm** [lidarr/LidarrAPI.Metadata#96]
Test Case:

https://musicbrainz.org/artist/cfd45526-701e-457a-b3bd-013506a890a6
lidarr:lidarr:cfd45526-701e-457a-b3bd-013506a890a6

Lidarr fails with `'`, MusicBrainz succeeds with the same. Lidarr only succeeds with explicit `’` (UTF8).

Possibly need https://github.com/metabrainz/postgresql-musicbrainz-unaccent on the Pg-side, which does a pretty good job of handling cases like this.

**Comment by Qstick** [comment]
`musicbrainz-unaccent` causes query time to go thru the roof from my quick testing, also its not used in the official search query from what I can see. <https://github.com/metabrainz/musicbrainz-server/blob/82c225e1114c6e173aaf67ddedeab7cc157fb0a9/lib/MusicBrainz/Server/Data/Search.pm>

Not sure that's our best route forward.

**Comment by rootwyrm** [comment]
Can you show me the `EXPLAIN ANALYZE` of the full query you tested with? It's a ... twitchy piece.

**Comment by Qstick** [comment]
Basically just wrapped the query of our current query with `musicbrainz-unaccent`

https://github.com/lidarr/LidarrAPI.Metadata/blob/develop/lidarrmetadata/sql/artist_search_name.sql

produces expected results, but not in a timely manner

**Comment by rootwyrm** [comment]
I really need to see the exact `EXPLAIN ANALYZE` output to see why it's misbehaving there. That's not something that is reproducible on my internal setup.

**Comment by dra2885** [comment]
For what it's worth, I've run into this same exact issue a few times recently. A potential work-around could be to let the user manually edit the search string for a given release (a la LazyLibrarian).
